// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Entities;

namespace Server.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20180809173442_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("Server.Entities.Badge", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.HasKey("ID");

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("Server.Entities.Class", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("StageID");

                    b.HasKey("ID");

                    b.HasIndex("StageID");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Server.Entities.Competition", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("Server.Entities.Punch", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BadgeID");

                    b.Property<int>("StationCode");

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("ID");

                    b.HasIndex("BadgeID");

                    b.ToTable("Punches");
                });

            modelBuilder.Entity("Server.Entities.Stage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CompetitionID");

                    b.HasKey("ID");

                    b.HasIndex("CompetitionID");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("Server.Entities.Class", b =>
                {
                    b.HasOne("Server.Entities.Stage")
                        .WithMany("Classes")
                        .HasForeignKey("StageID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Server.Entities.Punch", b =>
                {
                    b.HasOne("Server.Entities.Badge")
                        .WithMany("Punches")
                        .HasForeignKey("BadgeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Server.Entities.Stage", b =>
                {
                    b.HasOne("Server.Entities.Competition")
                        .WithMany("Stages")
                        .HasForeignKey("CompetitionID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
